### ISSUE TITLE
Graduate Courses

### ISSUE THREAD

**Issue by 1995parham** [aut-ce/.github#5]
@AliNazariii @MSadeghzadehG Is there any resource for the courses' code?

**Comment by AliNazariii** [comment]
@1995parham What do you mean? 
I don't get what you mean.

**Comment by 1995parham** [comment]
I mean the course codes for "درس‌های ارشد".

**Comment by AliNazariii** [comment]
Oh, I got it.
No, I checked all files from the last [faculty site](https://ceit.aut.ac.ir/autcms/tree/nodes.htm?id=1750794276&depurl=computer-engineering&lang=fa&cid=18299241) but I found nothing. 
I mean I found educational plans for them but they don't have any course code column.

**Comment by Bahador-Bakhshi** [comment]
In the department committees, we are reviewing and revising the master programs (similar to what have been done for the BS courses). 
There will be five programs (AI, SW, HW, Net, Security). In that programs, each course has a unique ID/Code. 
However, unfortunately, the programs have not been finalized yet, and I think they won't be finalized in the following months :-(
