### ISSUE TITLE
request for adding "how to graduate" repo

### ISSUE THREAD

**Issue by smahmadpanah** [aut-ce/.github#6]
اگه دوست داشتین این ریپو رو هم اینجا اضافه کنین و آپدیتش کنین:
https://github.com/smahmadpanah/HowToGraduateFromAUT

**Comment by 1995parham** [comment]
سلام دکتر، آره خیلی عالی می‌شود اگر خواستی منتقلش کنی چون به نظرم جایش اینجا خالی است.

**Comment by smahmadpanah** [comment]
You don’t have the permission to create public repositories on aut-ce
این پیغام رو میگیرم

**Comment by MSadeghzadehG** [comment]
سید ایمیلتون رو چک کنید

**Comment by smahmadpanah** [comment]
به نظرم اطلاعاتی که اونجا هست دیگه خیلی معتبر نباشه. لطفا در آپدیت نگه‌داشتنش کوشا باشید :)
