### ISSUE TITLE
How we can have a better introduction

### ISSUE THREAD

**Issue by 1995parham** [aut-ce/.github#7]
@AliNazariii @saman2000hoseini @smf8 I don't know the current members of our SSC so I mentioned you and I am sorry for that. there is a new feature in which we can say hello to people in our organization and wrote a simple one. it will be great if you can provide some images and a better introduction.

**Comment by AliNazariii** [comment]
It's ok Parham. 
I think [this](https://ce.aut.ac.ir/files/ce/yekta_program/albums/alb_26_75471e4/325.jpg) would be a good choice. It seems you are entering our faculty through this organization. :)

**Comment by AliNazariii** [comment]
and also @sarvenaz-srv is the chairwoman of our SSC.

**Comment by 1995parham** [comment]
I have invited her as owner.  @sarvenaz-srv Congratulations on this position and please add anybody you think can help us with the organization.

**Comment by sarvenaz-srv** [comment]
> I have invited her as owner. @sarvenaz-srv Congratulations on this position and please add anybody you think can help us with the organization.

Thank you for inviting me. I will add them ASAP.
